### ISSUE TITLE
DllNotFoundException 'DlibDotNetNativeDnn' failed in linux

### ISSUE THREAD

**Issue by timiil** [takuya-takeuchi/DlibDotNet#194]
# Summary of your issue

we can not run the example code in linux 

# Environment

an X64 cpu ,  native ubuntu / wsl ubuntu / docker ubuntu container 

Write your environment.

ubuntu 16.04
dotnet core 3.1 sdk

## Example code:

```
cd /home/
git clone https://github.com/takuya-takeuchi/DlibDotNet.git
cd DlibDotNet/example/FaceDetection

# modiy the FaceDetection.csproj file , changed to <TargetFramework>netcoreapp3.1</TargetFramework>

dotnet build  

dotnet run ./images/sample.png
```

## Output:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'DlibDotNetNativeDnn' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDlibDotNetNativeDnn: cannot open shared object file: No such file or directory
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor() in /home/timiil/DlibDotNet/src/DlibDotNet/PInvoke/NativeMethods.cs:line 40
   --- End of inner exception stack trace ---
   at DlibDotNet.NativeMethods.image_window_new()
   at DlibDotNet.ImageWindow..ctor() in /home/timiil/DlibDotNet/src/DlibDotNet/GuiWidgets/Widgets/ImageWindow.cs:line 16
   at FaceDetection.Program.Main(String[] args) in /home/timiil/DlibDotNet/examples/FaceDetection/Program.cs:line 22
```

## What did you intend to be?

make the code work just like in windows :)

**Comment by takuya-takeuchi** [comment]
@timiil 
You must modify *.csproj in example.
Because these example link src/DlibDotNet and it does not have native binary.

1. Remove reference DlibDotNet from *.csproj
2. Add nuget package to *.csproj

It should works.

**Comment by timiil** [comment]
thanks for your reply. but i had create an .net core console app, add DlibDotNet refrence from nuget, just call some simple api like Program.cs:
```
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            using (var detector = DlibDotNet.Dlib.GetFrontalFaceDetector()) ;
        }
    }
}

```

the ConsoleApp1.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DlibDotNet" Version="19.18.0.20200525" />
  </ItemGroup>

</Project>
```

dotnet build 
dotnet run 

running very perfect on windows, but failed in linux (neither wsl || native linux || docker container)
the fault is same :

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'DlibDotNetNativeDnn' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDlibDotNetNativeDnn: cannot open shared object file: No such file or directory

```


for your more information, i had check the linux /bin/Debug/netcoreapp3.1 output folder, the DlibDotNet.dll , DlibDotNetNative.so, DlibDotNetNativeDnn.so ... they are all EXIST. but the fault is still come. :(

**Comment by takuya-takeuchi** [comment]
@timiil 
You must check dependencies by ldd command.
Or install dependencies by https://github.com/takuya-takeuchi/DlibDotNet/blob/master/docker/base/ubuntu/16/cpu/x64/Dockerfile

**Comment by timiil** [comment]
thanks ~
```
apt-get update -y && apt-get install -y libopenblas-dev liblapack-dev libx11-6 
```

works like a charm~
