### ISSUE TITLE
"Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies

### ISSUE THREAD

**Issue by dashengjiadao** [takuya-takeuchi/DlibDotNet#195]
hi takuya,i very lucky for got ur dlibnotnet project,very thanks.
i using the project (examples\DnnMmodFindCars\Programs.cs) to build a demo program.
i got a error for "Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies" when ruing the program.

-------------------------------------------------------------------
E:\study\dlib\DlibDotNet-master\examples\DnnMmodFindCars\bin\Debug\netcoreapp2.0
System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL '**DlibDotNetNativeDnn**' or one of its dependencies: 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor() in E:\study\dlib\DlibDotNet-master\src\DlibDotNet\PInvoke\NativeMethods.cs:line 40
   --- End of inner exception stack trace ---
   at DlibDotNet.NativeMethods.proxy_deserialize_new(Byte[] fileName, Int32 fileNameLength)
   at DlibDotNet.ProxyDeserialize..ctor(String path) in E:\study\dlib\DlibDotNet-master\src\DlibDotNet\ProxyDeserialize.cs:line 26
   at DnnMmodFindCars.Program.Main() in E:\study\dlib\DlibDotNet-master\examples\DnnMmodFindCars\Program.cs:line 26

----------------------------------------------------------------------------------
this.NativePtr = NativeMethods.proxy_deserialize_new(str, str.Length);          <------this line..
-----------------------------------------------
i can't found DlibDotNetNativeDnn dll file.where is it?
i need ur help,thanks.

**Comment by takuya-takeuchi** [comment]
@dashengjiadao 
sorry late response.
Please check https://github.com/takuya-takeuchi/DlibDotNet/issues/194#issuecomment-638587467

**Comment by callah79** [comment]
I am having the same problem. It works on my machine with Ryzen 7 2700x. It doesn't on Intel G5400. They both support AVX instructions (someone mentioned this could be the problem). I had to downgrade to version 19.7, then it works on both machines.

**Comment by dashengjiadao** [comment]
> I am having the same problem. It works on my machine with Ryzen 7 2700x. It doesn't on Intel G5400. They both support AVX instructions (someone mentioned this could be the problem). I had to downgrade to version 19.17, then it works on both machines.

give me you email,i will send dlls to u

**Comment by dashengjiadao** [comment]
> > > I am having the same problem. It works on my machine with Ryzen 7 2700x. It doesn't on Intel G5400. They both support AVX instructions (someone mentioned this could be the problem). I had to downgrade to version 19.17, then it works on both machines.
> > 
> > 
> > give me you email,i will send dlls to u
> 
> [callah79@gmail.com](mailto:callah79@gmail.com)

check ur email!

**Comment by callah79** [comment]
> 
> 
> > > > I am having the same problem. It works on my machine with Ryzen 7 2700x. It doesn't on Intel G5400. They both support AVX instructions (someone mentioned this could be the problem). I had to downgrade to version 19.17, then it works on both machines.
> > > 
> > > 
> > > give me you email,i will send dlls to u
> > 
> > 
> > [callah79@gmail.com](mailto:callah79@gmail.com)
> 
> check ur email!

I didn't receive anything.

**Comment by takuya-takeuchi** [comment]
@callah79 
you can use 19.17 from nuget

**Comment by dashengjiadao** [comment]
> > > > > I am having the same problem. It works on my machine with Ryzen 7 2700x. It doesn't on Intel G5400. They both support AVX instructions (someone mentioned this could be the problem). I had to downgrade to version 19.17, then it works on both machines.
> > > > 
> > > > 
> > > > give me you email,i will send dlls to u
> > > 
> > > 
> > > [callah79@gmail.com](mailto:callah79@gmail.com)
> > 
> > 
> > check ur email!
> 
> I didn't receive anything.

sorry,i checked email,because gmail prohibit sending unsafe files.....
