### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

### ISSUE THREAD

**Issue by vikrant-bioenable** [takuya-takeuchi/DlibDotNet#215]
Error	System.DllNotFoundException: Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at DlibDotNet.Dlib.GetFrontalFaceDetector()
   at Bio_Face_Auth_Console.Program.AllignImage(String imagePath)

Hello Sir , please find above issue , i am facing on around 10 machnes out of 50 machines. 

System Configuration - windows 10 Pro - intel i5

**Comment by takuya-takeuchi** [comment]
@vikrant-bioenable 
Please note detail of difference between proper machine and wrong machine.
You install operating system and development tools by same step to all machine, right?
Almost machine works fine and it means that this issue occurs by environment you provided.

**Comment by vikrant-bioenable** [comment]
Hello Sir, I have checked configurations of both machine i.e. Working machine and non-working macine., Both have same configurations as below :
Windows 10 Pro Intel i5 7th generation

And I also installed dotnet core 3.1 framework runtime on all machines and aslo installed VC_redist.x64.exe on all machines.

still issue occurs on some machine's...

error as below : 

"System.DllNotFoundException: Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)\r\n   at DlibDotNet.NativeMethods.get_frontal_face_detector()\r\n   at DlibDotNet.Dlib.GetFrontalFaceDetector()\r\n   at Bio_Face_Auth_Console.Program.AllignImage(String imagePath)"

Please help me out of this situation... struggled alot to fix this issue with all posiibilities you had mentioned earlier

Thanks

**Comment by takuya-takeuchi** [comment]
@vikrant-bioenable 
Thanks for your new update.

> 0x8007045A

This error code is very hard to analysis.
But MSDN blogger teaches how to go through issue.

https://docs.microsoft.com/ja-jp/archive/blogs/tess/unable-to-load-dll-dllname-dll-a-dynamic-link-library-dll-initialization-routine-failed-0x8007045a

At least, your program can load DlibDotNet.Native.Dnn before calling GetFrontalFaceDetector.
So your machine could satisfy requirements to use DlibDotNet.Native.

Could you try the following things?

1. Call other method. ex. Dlib.GetNativeVersion()
2. Use Process Monitor to list up all dependencies and find out what library programs failed to load
