### ISSUE TITLE
macOS error: Unable to load shared library 'DlibDotNetNativeDnn' or one of its dependencies

### ISSUE THREAD

**Issue by Thecentury** [takuya-takeuchi/DlibDotNet#266]
# Summary of your issue

Hi Takuya, thank you for the great library!

I'm trying to use it on macOS but shared library `DlibDotNetNativeDnn` or one of its dependencies is not loaded.
Do you happen to know what I'm doing wrong or how this can be fixed?

# Environment

macOS 10.15.7

# What did you do when you faced the problem?

The code reproducing the issue is in https://github.com/Thecentury/FaceRecognitionRepro.
I've added references to
```xml
<PackageReference Include="DlibDotNet" Version="19.21.0.20210302" />
<PackageReference Include="FaceRecognitionDotNet" Version="1.3.0.5" />
```

## Example code:

```cs
// The next line throws an exception:

// Unhandled exception. System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
// ---> System.DllNotFoundException: Unable to load shared library 'DlibDotNetNativeDnn' or one of
//     its dependencies.In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES
//     environment variable:
// dlopen(libDlibDotNetNativeDnn, 1): image not found
using (var detector = DlibDotNet.Dlib.GetFrontalFaceDetector())
{
}
```

## Output:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'DlibDotNetNativeDnn' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libDlibDotNetNativeDnn, 1): image not found
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at DlibDotNet.Dlib.GetFrontalFaceDetector()
   at FaceRecognitionRepro.Program.Main(String[] args)
```

Here is also an output of `otool -L` for `libDlibDotNetNative.dylib` and `libDlibDotNetNativeDnn.dylib` (it's, as far as I understand, a macOS alternative of a Linux `ldd`):

```
$ otool -L libDlibDotNetNative.dylib                                                                                                                                                libDlibDotNetNative.dylib:
	@rpath/libDlibDotNetNative.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/X11/lib/libSM.6.dylib (compatibility version 7.0.0, current version 7.1.0)
	/opt/X11/lib/libICE.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/X11/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/local/opt/giflib/lib/libgif.dylib (compatibility version 0.0.0, current version 7.2.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 321.1.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

```
otool -L libDlibDotNetNativeDnn.dylib                                                                                                                                             libDlibDotNetNativeDnn.dylib:
	@rpath/libDlibDotNetNativeDnn.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/X11/lib/libSM.6.dylib (compatibility version 7.0.0, current version 7.1.0)
	/opt/X11/lib/libICE.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/X11/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/local/opt/giflib/lib/libgif.dylib (compatibility version 0.0.0, current version 7.2.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 321.1.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

**Comment by Thecentury** [comment]
After running `otool -L` for the dependencies of `ibDlibDotNetNative.dylib`, I discovered that the `giflib` was not installed on my machine. After installing it via `brew install giflib`, the `DlibDotNet.Dlib.GetFrontalFaceDetector()` method works fine.
So I'll close this issue.
