### ISSUE TITLE
How to dockerize an app that uses this library

### ISSUE THREAD

**Issue by ffrankozz** [takuya-takeuchi/DlibDotNet#276]
# Summary of your issue
I created a simple console app to get facial landmarks on a Wİndows 10 machine.
I get the facial landmarks of an input image and write the landmarks on an output image. 
The app is working without a problem. However, when I create the docker image of the console app and run the docker image 
I get an exception. 
 Unhandled exception. System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'DlibDotNetNativeDnn' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDlibDotNetNativeDnn: cannot open shared object file: No such file or directory
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at DlibFaceProject.Program.Main(String[] args) in /src/DlibFaceProject/Program.cs:line 18

Line 18 is the first place where we call a DLib method.

**Comment by takuya-takeuchi** [comment]
@ffrankozz 
DlibDotNetNativeDnn depends on some library so you must install them into container.
`ld -v` command could tell you what libraries are missing.

And You can refer https://github.com/takuya-takeuchi/DlibDotNet/wiki/Tutorial-for-Linux to resolve issue.

**Comment by ffrankozz** [comment]
@takuya-takeuchi Thank you very much  for your reply. I will have a look at the link you refer  to. In the mean time, where do I run that "ldd -v"  command?    Is it a command  to run in the root of the project?

**Comment by takuya-takeuchi** [comment]
I'm not sure how you installed dlibdotnet.
but if using nuget, you can see /root/.nuget/package/dlibdotnet.
And you can find libdlibdonetnativednn.so and invoke `ldd -v libdlibdotnetnativednn.so`

**Comment by ffrankozz** [comment]
@takuya-takeuchi Thank you very much for the suggestions. It is strange that everything is fine with normal desktop build and run. But when dockerized, the docker image, when run,  reads the input  picture file, data file which are in the project root but somehow I cannot see the saved output image in the current directory. I changed the output picture saving location to somewhere in the local drive, but still no output picture there. I can read the bytes of the output file and write on the console. I am sure the output image is being created. But somehow not visible. I now it is not a dlibdotnet issue but I just wanted to share it. Perhaps, mounting app directory will help. I will try that next.
