### ISSUE TITLE
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.

### ISSUE THREAD

**Issue by TrojanOlx** [takuya-takeuchi/DlibDotNet#80]
# 

System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.

# 

Windows 10 pro 64-bit (10.0, Build 17134)
Intel(R) Core(TM) i5-8400 CPU @2.80ghz (6 CPUs), ~ 2.8ghz
24576 MB of RAM
No separate graphics card

Microsoft Visual Studio Professional 2017
Version 15.9.3

dotnet core SDK 2.1.6

# 

I publish my code, and I run it

# Example code:

`public static ShapePredictor _SP
        {
            get
            {
                if (_sp == null)
                {
                  var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ShapeModel", "shape_predictor_5_face_landmarks.dat");
                    _sp = ShapePredictor.Deserialize(path);
                }
                return _sp;
            }
        }`

#

- 
I worked fine in the "Debug" directory and under "Release\netcoreapp2.1\publish", but I copied all the files in publish to my desktop . It reported an error。
If necessary, I can send you a copy of my complete code.

This problem has been bothering me for a long time and I'm not sure if it's a (C++/CLI and standard C++) problem.

- It would be nice to find out what the problem is and fix it.
-

**Comment by TrojanOlx** [comment]
Sorry, I think I have found the problem. My catalogue is not in English.
But I found a problem again, publish later:
`System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies:   can't find the specified module.`

The version is: 19.16.0.20190122
There is no such problem on 19.15.0.20181008

**Comment by TrojanOlx** [comment]
Sorry, I think I have found the problem. My catalogue is not in English.
But I found a problem again, publish later:
`System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: can't find the specified module.` 

The version is: 19.16.0.20190122
There is no such problem on 19.15.0.20181008

**Comment by takuya-takeuchi** [comment]
Could try the following program?
[#80.zip](https://github.com/takuya-takeuchi/DlibDotNet/files/2792144/80.zip)

1. Unzip to directory and you can see directory '#80'
2. Copy shape_predictor_5_face_landmarks.dat to #80

## Test dotnet run command

````cmd
cd #80
TestRun.bat
````
## Test dotnet publish  command and execute exe file

````cmd
cd #80
TestRunPublish.bat
````

This program is very simple.
bat command add DlibDotNet package and build and run the following.

````csharp
using System;
using System.Collections.Generic;
using System.Linq;
using DlibDotNet;

namespace Test
{

    internal class Program
    {

        private static void Main(string[] args)
        {
            var sp = ShapePredictor.Deserialize(args[0]);
            Console.WriteLine(sp);
        }
	}
	
}
````
After do, you can see 'DlibDotNet.ShapePredictor' in console.

**Comment by takuya-takeuchi** [comment]
At least, I did not face any problem.

**Comment by TrojanOlx** [comment]
Thank you. I've got a problem.
By the way, I released it using VS2017
The following configuration will cause an error when I publish it.


![image](https://user-images.githubusercontent.com/43137352/51727588-a9171400-20a7-11e9-863a-5a2132760532.png)

Sorry, the third behavioral framework dependence

run

``dotnet Test.dll ``

```
System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: The specified module could not be found。 (Exception from HRESULT: 0x8007007E)
   at DlibDotNet.NativeMethods.loss_metric_deserialize(Byte[] fileName, Int32 type, IntPtr& net)
   at DlibDotNet.Dnn.LossMetric.Deserialize(String path, Int32 networkType)
   at Test.Program.get__NET() in E:\EightyPercent\Test\Test\Program.cs:line 51
   at Test.Program.Main(String[] args) in E:\EightyPercent\Test\Test\Program.cs:line 17
```
My code looks like this:

```
namespace Test
{

    internal class Program
    {
        private static ShapePredictor _sp = null;
        private static LossMetric _net = null;

        private static void Main(string[] args)
        {
            try
            {
                Console.WriteLine(_SP);
                Console.WriteLine(_NET);
            }
            catch (Exception ex)
            {

                Console.WriteLine(ex);
            }

        }

        public static ShapePredictor _SP
        {
            get
            {
                if (_sp == null)
                {
                    string path = "shape_predictor_5_face_landmarks.dat";
                    _sp = ShapePredictor.Deserialize(path);
                }
                return _sp;
            }
        }

        
        public static LossMetric _NET
        {
            get
            {
                if (_net == null)
                {
                    string path = "dlib_face_recognition_resnet_model_v1.dat";
                    _net = LossMetric.Deserialize(path);
                }
                return _net;
            }
        }
    }
}
```
But I can use this configuration to publish it

![image](https://user-images.githubusercontent.com/43137352/51727691-1dea4e00-20a8-11e9-9f5b-04a0a3502689.png)

This is portable.

Another problem is that I got the same error when I put these files on Linux, but it works fine on Windows 10

I want to know what environments are required to run on Linux

**Comment by takuya-takeuchi** [comment]
DlibDotNetNativeDnn.dll depends on the following libraries.

````cmd
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\dumpbin.exe" /dependents DlibDotNetNativeDnn.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file DlibDotNetNativeDnn.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
````

Do you install Visual C++ Redistribution Package 2015?
(Sorry. I thought I linked VC++2017 runtime but it was misunderstanding)

> dotnet Test.dll

I executed the similar above command in the following which contains these files.

### bin\Release\netcoreapp2.0\win-x64

* #80.deps.json
* #80.dll
* #80.pdb
* #80.runtimeconfig.dev.json
* #80.runtimeconfig.json
* DlibDotNetNative.dll
* DlibDotNetNativeDnn.dll

### bin\Release\netcoreapp2.0\publish

* #80.deps.json
* #80.dll
* #80.pdb
* #80.runtimeconfig.json
* .keepfolder
* DlibDotNet.dll
* DlibDotNetNative.dll
* DlibDotNetNativeDnn.dll


There was no problem.

**Comment by TrojanOlx** [comment]
Thank you, *#80 is normal in Windows, but I put *#80 running on Linux, there is this error, I can not find the reason, may I ask if you have tried on Linux?

```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'DlibDotNetNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDlibDotNetNative: cannot open shared object file: No such file or directory
   at DlibDotNet.NativeMethods.deserialize_shape_predictor(Byte[] filName)
   at DlibDotNet.ShapePredictor.Deserialize(String path)
   at Test.Program.Main(String[] args) in F:\facephsh\#80\Program.cs:line 14
```


```dotnet publish -c Release```

This is the generated files

```
runtimes
*#80.deps.json  
*#80.pdb                 
*#80.dll        
*#80.runtimeconfig.json  
DlibDotNet.dll   
DlibDotNetNative.dll      
DlibDotNetNativeDnn.dll  
shape_predictor_5_face_landmarks.dat
```
This is my virtual machine information

```
Linux localhost.localdomain 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.6.1810 (Core)

2.0.3 [/usr/share/dotnet/sdk]
2.1.503 [/usr/share/dotnet/sdk]
2.2.103 [/usr/share/dotnet/sdk]
```

**Comment by takuya-takeuchi** [comment]
Ok. I did not prepare CentOS virtual machine.
So I will create it and try program.

**Comment by takuya-takeuchi** [comment]
I was able to reproduce your issue on Ubuntu 16.04.5 and CentOS 7.6.
But it works fine on MacOSX. It is weird.

**Comment by takuya-takeuchi** [comment]
Ok. It is not weird.

````sh
./libDlibDotNetNative.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./libDlibDotNetNative.so)
        linux-vdso.so.1 =>  (0x00007ffe86198000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3580966000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f358062c000)
        libpng16.so.16 => not found
        libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f35803d3000)
        libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007f35801b1000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f357f9cd000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f357f64b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f357f342000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f357f12c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f357ed62000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3581fd7000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f357eb40000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f357e93c000)
        libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f357e39e000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f357e073000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f357de35000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f357dc31000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f357da2b000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f357d7ec000)
````

You may install libpng and need to update GLIBCXX.

You can refer https://stackoverflow.com/questions/43070900/version-glibcxx-3-4-22-not-found

After install and update,

````sh
takuya@Ubuntu16-04-4:~/work/OpenSource/tmp/#80/bin/x64/Release/netcoreapp2.0/linux-x64/publish$ ldd libDlibDotNetNative.so
        linux-vdso.so.1 =>  (0x00007ffd41be3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb075da8000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb075a6e000)
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fb07583d000)
        libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fb0755e4000)
        libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007fb0753c2000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fb074bde000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb074852000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb074549000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb074331000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb073f67000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb077419000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb073d45000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb073b41000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb073927000)
        libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007fb073389000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fb073058000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fb072e1a000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb072c16000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb072a10000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fb0727d0000)
````

It works fine!!!

**Comment by TrojanOlx** [comment]
Thank you. I'll have a try.

**Comment by TrojanOlx** [comment]
```ldd libDlibDotNetNative.so ```  all the missing ones  install
 install libpng and update GLIBCXX
#80 has been successfully executed.And the output 
```DlibDotNet ShapePredictor```
But then I found another problem

```
DlibDotNet.ShapePredictor

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'DlibDotNetNativeDnn' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDlibDotNetNativeDnn: cannot open shared object file: No such file or directory
   at DlibDotNet.NativeMethods.loss_metric_deserialize(Byte[] fileName, Int32 type, IntPtr& net)
   at DlibDotNet.Dnn.LossMetric.Deserialize(String path, Int32 networkType)
   at Test.Program.Main(String[] args) in /home/trojan/Desktop/TestLinux/Program.cs:line 15
Aborted (core dumped)

```

The code looks like this

```
using System;
using DlibDotNet;
using DlibDotNet.Dnn;

namespace Test
{

    internal class Program
    {

        private static void Main(string[] args)
        {
            var sp = ShapePredictor.Deserialize("shape_predictor_5_face_landmarks.dat");
            Console.WriteLine(sp);
            var net = LossMetric.Deserialize("dlib_face_recognition_resnet_model_v1.dat");
            Console.WriteLine(net);
        }
     }
	
}
```

Is it because I still have some unconfigured environment?

**Comment by TrojanOlx** [comment]
This is the console output.

```
ldd libDlibDotNetNativeDnn.so 
./libDlibDotNetNativeDnn.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./libDlibDotNetNativeDnn.so)
	linux-vdso.so.1 =>  (0x00007fff7ad80000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f89cbead000)
	libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007f89cbc8b000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f89cb4a7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f89cb11a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f89cae11000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f89cabf9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f89ca82e000)
	/lib64/ld-linux-x86-64.so.2 (0x000055de72aaf000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f89ca290000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f89c9f5f000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f89c9d20000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f89c9ae0000)
```

```
ldd libDlibDotNetNative.so 
	linux-vdso.so.1 =>  (0x00007ffd39748000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f18b300b000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f18b2cd1000)
	libpng16.so.16 => /usr/local/lib/libpng16.so.16 (0x00007f18b2a9e000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f18b2844000)
	libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007f18b2622000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f18b1e3e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f18b1ab1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f18b17a8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f18b1590000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f18b11c5000)
	/lib64/ld-linux-x86-64.so.2 (0x00005649786c0000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f18b0fa3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f18b0d9f000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f18b0b84000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f18b05e6000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f18b02b5000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f18b0076000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f18afe72000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f18afc6b000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f18afa2b000)
```

**Comment by takuya-takeuchi** [comment]
> version `GLIBC_2.27'

I guess It is same issue.
But I built DlibDotNet on Ubuntu 18. so other linux may not have proper glibc.

https://developer.mozilla.org/ja/docs/Mozilla/Firefox/Linux_compatibility_matrix may be useful for us.

**Comment by TrojanOlx** [comment]
Do you mean using glibc_2.13?
You can download it here
http://ftp.gnu.org/gnu/glibc/ 
```
wget http://ftp.gnu.org/gnu/glibc/glibc-2.13.tar.gz
tar -zxf glibc-2.13.tar.gz
mkdir glibc-build
cd glibc-build
../glibc-2.13/configure --prefix=/usr/lib64/glibc-2.13
make
make install
```
Or try Debian 7

But I don't have time to try right now.

**Comment by takuya-takeuchi** [comment]
FYI, you can build DlibDotNet.Native and DlibDotNet.Native.Dnn on system you want to let it run. Perhaps, it is easy.
You can install development tools and latest cmake. Then you run BuildLinux.sh.

I was able to build and run the #80 program.

**Comment by TrojanOlx** [comment]
Thank you @takuya-takeuchi. The problem has been solved.
Do it your way:

1. Copy #80 into production.

2. Install libpng and update GLIBCXX

3. Will libDlibDotNetNative. So and libDlibDotNetNativeDnn. So dependent on all installed.
```
root@f7203148c7d9:/app# ldd libDlibDotNetNative.so
        linux-vdso.so.1 =>  (0x00007fff082cd000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd0e079d000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd0e0463000)
        libpng16.so.16 => /usr/local/lib/libpng16.so.16 (0x00007fd0e0230000)
        libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007fd0e000e000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fd0df82a000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd0df4a8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd0df19f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd0def89000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd0debbf000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd0e1dec000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd0de99d000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd0de799000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd0de57f000)
        libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007fd0ddfe1000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fd0ddcb6000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fd0dda78000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd0dd874000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd0dd66e000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fd0dd42f000)
root@f7203148c7d9:/app# ldd libDlibDotNetNativeDnn.so
        linux-vdso.so.1 =>  (0x00007ffd435f1000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f379e90e000)
        libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007f379e6ec000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f379df08000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f379db86000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f379d87d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f379d667000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f379d29d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f379f659000)
        libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f379ccff000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f379c9d4000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f379c796000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f379c557000)
```

4. Build dlibdotnet. Native and dlibdotnet. Native.Dnn on the running system.


I also created a Docker: "dlibdotnet-ubuntu-remote"
I can run inside of this Docker.The runtime environment is dotnet Core 2.1.
It USES libDlibDotNetNative. So and libDlibDotNetNativeDnn. So I have to upload.

```https://github.com/TrojanOlx/DlibdotnetFiles.git```


The problem that had been bothering me for so long was finally solved.
